const flagMap: { [key: string]: string } = {
  American: "/American.svg",
  British: "/British.svg",
  Canadian: "/Canadian.svg",
  Chinese: "/Chinese.svg",
  Croatian: "/Croatian.svg",
  Dutch: "/Dutch.svg",
  Egyptian: "/Egyptian.svg",
  Filipino: "/Filipino.svg",
  French: "/French.svg",
  Greek: "/Greek.svg",
  Indian: "/Indian.svg",
  Irish: "/Irish.svg",
  Italian: "/Italian.svg",
  Jamaican: "/Jamaican.svg",
  Japanese: "/Japanese.svg",
  Kenyan: "/Kenyan.svg",
  Malaysian: "/Malaysian.svg",
  Mexican: "/Mexican.svg",
  Moroccan: "/Moroccan.svg",
  Polish: "/Polish.svg",
  Portuguese: "/Portuguese.svg",
  Russian: "/Russian.svg",
  Spanish: "/Spanish.svg",
  Thai: "/Thai.svg",
  Tunisian: "/Tunisian.svg",
  Turkish: "/Turkish.svg",
  Ukrainian: "/Ukrainian.svg",
  Vietnamese: "/Vietnamese.svg",
  Unknown: "",
};

export const getFlagUrl = (area: string): string | null => flagMap[area] || null;
